INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Piccadilly', 'P1', '1Q');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Piccadilly', 'P2', '1Q');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Piccadilly', 'P3', '1Q');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Piccadilly', 'P4', '2Q');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Piccadilly', 'PS', '2Q');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Piccadilly', 'P6', '2Q');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Cambridge', 'C1', '1K');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Cambridge', 'C2', '1K');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Cambridge', 'C3', '1K');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Westminster', 'W1', '1K');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Westminster', 'W2', '1K');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Westminster', 'W3', '1K');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Westminster', 'W4', '1K');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Westminster', 'W5', '2D');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Westminster', 'W6', '2D');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Westminster', 'W7', '2D');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Oxford', 'O1', '1K');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Oxford', 'O2', '1K');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Oxford', 'O3', '1Q');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Oxford', 'O4', '1Q');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Oxford', 'O5', '1Q');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Victoria', 'V1', '1K');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Victoria', 'V2', '2D');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Victoria', 'V3', '2D');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Manchester', 'M1', '1K');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Manchester', 'M2', '1K');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Manchester', 'M3', '1K');

INSERT INTO ROOM (NAME, ROOM_NUMBER, BED_INFO) VALUES ('Manchester', 'M4', '1K');

INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, ADDRESS, COUNTRY, STATE, PHONE_NUMBER) VALUES ('Adams', 'Roy', 'radams1v@gmail.com', 'United States', '2872 Marquette Street', 'NY', '1-(235)314-9823');
INSERT INTO GUEST (LAST_NAME, FIRST_NAME, EMAIL_ADDRESS, ADDRESS, COUNTRY, STATE, PHONE_NUMBER) VALUES ('Adams', 'Martin', 'radams1v@gmail.com', 'China', '2872 Marquette Street', 'NY', '9-(225)344-9623');

INSERT INTO RESERVATION (ROOM_ID, GUEST_ID, RES_DATE) VALUES ((SELECT ROOM_ID FROM ROOM WHERE ROOM_NUMBER = 'C2'), (SELECT GUEST_ID FROM GUEST WHERE FIRST_NAME = 'Roy'), '2022-01-01');

